[package]
name = "speedtest"
version = "1.1.1"
authors = ["nbrandolino nickbrandolino134@gmail.com"]
edition = "2021"

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
clap = "4.0"
